server:
  servlet:
    context-path: /dataprocessing

spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/dataprocessing
    username: postgres
    password: Welcome123

logging:
  level:
    root: "INFO"
  register-shutdown-hook: true
  file:
    name: D://dataprocessing.log

